### ISSUE TITLE
Замечания по первой итерации

### ISSUE THREAD

**Issue by akhtyamovpavel** [JungleTryne/HeartStone#1]
Привет!

Посмотрел задание, по архитектуре - все супер! Я хотел бы оставить некоторые замечания:

- [x] `.idea` - вынести в `.gitignore`, это метаинформация об проекте
- [x] - https://github.com/JungleTryne/HeartStone/blob/master/unitSystem/UnitsFabrics.py#L13 - лучше создать singleton для генерации случайных чисел
- [x] - https://github.com/JungleTryne/HeartStone/blob/master/unitSystem/Units.py#L11 - я бы посоветовал вынести эти константы в отдельный файлик, чтобы можно было менять только конфигурационный файл, а код не менять
- [x] - https://github.com/JungleTryne/HeartStone/blob/master/unitSystem/unitBase.py#L37 - лучше везде переделать под `snake_case`
- [x] - https://github.com/JungleTryne/HeartStone/blob/master/unitSystem/unitBase.py - лучше `unit_base.py`

В остальном - все отлично! Жду исправлений!

**Comment by JungleTryne** [comment]
Пункты исправлены, см второй коммит на мастере
P.S. да, я коммичу на мастер, зато у меня код coverage 98%
